.catalog:
  name: "Percona XtraDB Cluster"
  version: 5.7.17-29.20-rancher1
  description: |
    Percona XtraDB Cluster 5.7.17
  questions:
    - variable: "scale_num"
      description: Desired cluster size. 3, 5, or 7 are good choices. You will need this many hosts to reach your desired scale.
      label: Number of Nodes PXC
      required: true
      default: 3
      type: int
    - variable: "etcd_service"
      label: "Etcd"
      description: Service link to Etcd. This will be mapped to the container as 'etcd'
      type: "service"
      required: true
    - variable: "cluster_name"
      type: string
      required: true
      label: "Cluster Name"
      description: Cluster name for WSREP and Etcd
    - variable: "storage_driver"
      label: "Storage Driver"
      description: Storage driver for Percona data (can be empty string)
      type: string
      required: false
    - variable: "mysql_root_password"
      type: string
      required: true
      label: "MySQL Root Password"
      description: Password given to the root mysql user
      default: "password"
    - variable: "pxc_sst_password"
      type: string
      required: true
      label: "PXC SST Password"
      description: Password given to the sst mysql user
      default: "s3cretPass"
    - variable: "mysql_database"
      type: string
      required: false
      label: "MySQL Database Name"
      description: MySQL database to create
    - variable: "mysql_user"
      type: string
      required: false
      description: MySQL user for the created database
      label: "MySQL DB User"
    - variable: "mysql_password"
      type: string
      required: false
      label: "MySQL DB Password"
      description: Password for the MySQL user of the created database
    - variable: "volume_data"
      description: "Volume to save mysql data (must end with a colon ':' if specified)."
      label: "Data volume:"
      default: ""
      type: "string"
    - variable: SC_LABEL_VALUE
      label: Scheduler Host Label
      description: |
        Enter a name=value pair of any required host label you may want in order to bind your services to.
      type: string
pxc:
  scale: ${scale_num}
  retain_ip: true
  health_check:
    port: 8000
    interval: 2000
    unhealthy_threshold: 3
    strategy: none
    request_line: GET / HTTP/1.1
    healthy_threshold: 2
    response_timeout: 2000
pxc-lb:
  scale: 1
  retain_ip: true
  load_balancer_config: {}
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000