version: '2'
catalog:
  name: Minio
  version: 0.6.0
  minimum_rancher_version: v1.2.0
  questions:
    - variable: "MINIO_SCALE"
      description: "Number of minio nodes."
      label: "Minio Nodes"
      required: true
      default: 1
      type: enum
      options:
        - 1
        - 4
        - 6
        - 8
        - 10
        - 12
        - 14
        - 16
    - variable: "MINIO_DISKS"
      description: "Number of disks per node"
      label: "Disks Per Node"
      required: true
      type: enum
      default: 1
      options:
        - 1
        - 2
        - 4
    - variable: "DISK_BASE_NAME"
      description: "The base name for each disk"
      label: "Disk base name"
      type: "string"
      required: true
      default: "disk"
    - variable: "VOLUME_DRIVER"
      description: "Docker driver to store volume or base path for each disks"
      label: "Volume drver / Path"
      type: "string"
      required: true
      default: "local"
    - variable: "MINIO_ACCESS_KEY"
      description: "The key to connect on minio"
      label: "Minio key"
      required: true
      type: "string"
    - variable: "MINIO_SECRET_KEY"
      description: "The secret key to connect on minio"
      label: "Minio secret key"
      required: true
      type: "password"
    - variable: "CONFD_BACKEND"
      description: "The confd backend to grab config"
      label: "Confd backend"
      required: true
      default: "env"
      type: "string"
    - variable: "CONFD_NODES"
      description: "The confd nodes"
      label: "Confd nodes"
      required: false
      type: "string"
    - variable: "CONFD_PREFIX"
      description: "The confd prefix"
      label: "Confd prefix"
      required: true
      default: "/minio"
      type: "string"
    - variable: SC_LABEL_VALUE
      label: Scheduler Host Label
      description: |
        Enter a name=value pair of any required host label you may want in order to bind your services to.
      type: string
      
services:
  minio-server:
    scale: ${MINIO_SCALE}
    retain_ip: true
    health_check:
      port: 9000
      interval: 5000
      unhealthy_threshold: 3
      request_line: ''
      healthy_threshold: 2
      response_timeout: 5000
  minio-lb:
    scale: 1
    start_on_create: true
    retain_ip: true
    load_balancer_config: {}
    lb_config:
      port_rules:
      - priority: 1
        protocol: http
        service: minio-server
        source_port: 9000
        target_port: 9000
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      interval: 2000
