version: '2'
catalog:
  name: Redmine
  version: 0.1.2
  description: |
    Redmine
  questions:
  - variable: "REDMINE_PUBLISH_DOMAIN"
    description: "FQDN to use for the Redmine server"
    label: "REDMINE Domain"
    required: true
    default: "redmine.local"
    type: "string"
  - variable: "TZ"
    description: "Timezone to use for the server"
    label: "Timezone"
    required: true
    default: "America/Chicago"
    type: "string"
  - variable: "DB_PASS"
    description: "Database Password to use for the server"
    label: "DB Password"
    required: true
    default: ""
    type: "password"
  - variable: "REDMINE_SECRET_TOKEN"
    description: "REDMINE_SECRET_TOKEN"
    label: "REDMINE_SECRET_TOKEN"
    required: true
    default: ""
    type: "password"
  - variable: "VOLUME_DRIVER"
    description: "The VOLUME driver to associate with this server"
    label: "VOLUME Driver"
    required: true
    default: "rancher-nfs"
    type: enum
    options:
      - local
      - pxd
      - rancher-nfs
      - rancher-efs
      - rancher-ebs
  - variable: "REDMINE_PUBLISH_DOMAIN"
    description: "FQDN to use for the Redmine server"
    label: "REDMINE Publish Domain"
    required: true
    default: "redmine.local"
    type: "string"
  - variable: "REDMINE_PUBLISH_SCHEMA"
    description: "Publish schema" 
    label: "REDMINE Publish Schema:"
    required: true
    default: "https"
    type: "enum"
    options:
      - http
      - https
  - variable: "REDMINE_PUBLISH_NAME"
    label: "REDMINE Publish Name"
    description: |
      Set publish fqdn for Redmine server.
    required: true
    type: "string"
    default: "redmine.local"
  - variable: "REDMINE_PUBLISH_PORT"
    label: "REDMINE Publish Port"
    description: |
      Set port if you want publish external port for Redmine server.
    required: true
    type: "int"
    default: 8080
  - variable: "SSL_CERT"
    description: "Select SSL certificate." 
    label: "SSL certificate:"
    required: true
    default: ""
    type: "certificate"
  - variable: "SMTP_ENABLED"
    description: "SMTP Enabled" 
    label: "REDMINE SMTP Enabled:"
    required: true
    default: "false"
    type: "enum"
    options:
      - "true"
      - "false"
  - variable: "SMTP_DOMAIN"
    description: "SMTP Domain" 
    label: "REDMINE SMTP Domain:"
    required: true
    default: "www.gmail.com"
    type: "string"
  - variable: "SMTP_HOST"
    description: "SMTP Host" 
    label: "REDMINE SMTP Host:"
    required: true
    default: "smtp.gmail.com"
    type: "string"
  - variable: "SMTP_PORT"
    description: "SMTP Port" 
    label: "REDMINE SMTP Port:"
    required: true
    default: 587
    type: "int"
  - variable: "SMTP_USER"
    description: "SMTP User" 
    label: "REDMINE SMTP User:"
    required: false
    default: ""
    type: "string"
  - variable: "SMTP_PASS"
    description: "SMTP Password" 
    label: "REDMINE SMTP Password:"
    required: false
    default: ""
    type: "string"

services:
  redmine:
    scale: 1
    retain_ip: true
    health_check:
      healthy_threshold: 2
      response_timeout: 5000
      port: 80
      unhealthy_threshold: 3
      interval: 5000
      strategy: recreate
      request_line: GET / # HTTP/1.0
  redmine-lb:
    scale: 1
    retain_ip: true
    lb_config:
      certs: []
      default_cert: ${SSL_CERT}
      port_rules:
      - hostname: ${REDMINE_PUBLISH_DOMAIN}
        protocol: ${REDMINE_PUBLISH_SCHEMA}
        service: redmine
        source_port: ${REDMINE_PUBLISH_PORT}
        target_port: 80
    health_check:
      port: 42
      interval: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000
